[tool.poetry]
name = "certbot-dns-binarylane"
version = "0.0.1"
description = "A BinaryLane DNS plugin for Cerbot to authenticate and retrieve Lets Encrypt certificates"
authors = ["Nicholas Ciechanowski <nicholasaciechanowski@gmail.com>", "Karl Goetz <karl+certbot@medeopolis.au>"]
license = "Apache-2.0"
readme = "README.md"
# repository = ""

packages = [{ include = "certbot_dns_binarylane.py" }]

[tool.poetry.dependencies]
python = "^3.10"
certbot = "^2.8.0"
requests = "^2.32.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."certbot.plugins"]
"dns-binarylane" = "certbot_dns_binarylane:Authenticator"

